#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

void add(int a, int b) {
  cout << "+ " << a << " " << b << endl;
  int p;
  cin >> p;
  if (p == -1) {
    exit(0);
  }
}

// generated by oj-template v4.8.1
// (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int n;
  std::cin >> n;
  vector<int> index(n);
  iota(ALL(index), 1);
  sort(ALL(index), [](const int &a, const int &b) {
    cout << "? " << a << " " << b << endl;
    int q;
    cin >> q;
    if (q == -1) {
      exit(0);
    }
    return q == 1;
  });
  add(index[0], index[n - 1]);
  for (int i = 0; i < n / 2; i++) {
    add(index[i], index[n - i - 1]);
  }
  int idx = n + 1;
  for (int i = n; i < n / 2 + n; i++) {
    add(index[i], idx);
    idx++;
  }
  if (n % 2 == 1) {
    add(index[n / 2], idx);
  }
  cout << "!" << endl;
  return 0;
}
