#include <algorithm>
#include <bits/stdc++.h>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(int N, const std::vector<std::string> &S) {
  sort(S.begin(), S.end());
  string previous;
  vector<string> first = {"H", "D", "C", "S"};
  vector<string> second = {"A", "2", "3", "4", "5", "6", "7",
                           "8", "9", "T", "J", "Q", "K"};
  for (int i = 0; i < N; i++) {
    string s = S[i];
    if (s == previous) {
      return false;
    }
    for (int j = 0; j < 4; j++) {
      if (s.substr(0, 1) == first[j]) {
        break;
      }
      if (j == 3) {
        return false;
      }
    }
    for (int k = 0; k < 13; k++) {
      if (s.substr(1, 1) == second[k]) {
        break;
      }
      if (k == 12) {
        return false;
      }
    }
    previous = s;
  }

  return true;
}

// generated by oj-template v4.8.1
// (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int N;
  std::cin >> N;
  std::vector<std::string> S(N);
  REP(i, N) { std::cin >> S[i]; }
  auto ans = solve(N, S);
  std::cout << (ans ? YES : NO) << '\n';
  return 0;
}
